import { createSlice } from '@reduxjs/toolkit';
import model from '../models/uxpServerModel.js';
import { createAsyncThunk } from '@reduxjs/toolkit';

/* - - - - - - - - - - THUNKS - - - - - - - - - - -
A "thunk" is an async function, often used as fetchers. 
Thunks are the only place Redux accepts async logic.
We will use thunks to fetch data and dispatch actions. 
If we use createAsyncThunk, then the error and status 
handling is autogenerated, see "extraReducers".
*/
export const fetchResources = createAsyncThunk('resources/fetchAll', async () => {
  const data = await model.getAllResources();
  return data;
});

/* - - - - - - - - - - - REDUCERS - - - - - - - - - - 
A "reducer" is a function that calculates the new state based 
on the dispatched action.
Since we pass these into createSlice below, we can use mutable 
logic, which looks a lot simpler. 
The extraReducers handle auto generated actions from async thunks.
*/
const reducers = {
};
const extraReducers = {
  [fetchResources.pending]: (state, action) => {
    state.status = 'loading'
  },
  [fetchResources.fulfilled]: (state, action) => {
    state.status = 'success'
    state.list = action.payload;
  },
  [fetchResources.rejected]: (state, action) => {
    state.status = 'failed'
  }
}

/* - - - - - - - - - - SELECTORS - - - - - - - - - 
A "selector" is a function that selects certain values 
from the state. We can define them in the React comp,
but here is better for complex selectors. 
*/
export const getAllResources = state => state.resources.list;
export const getFetchStatus = state => state.resources.status;
export const getResourcesByFlag = (state, flagNames) => {
  let list = getAllResources(state);
  flagNames.forEach(flag => {
    list = list.filter(r => r[flag] === true);
  });
  return list;
}
export const getResourcesBySearch = (state, searchText) => {
  return getAllResources(state);
}
export const getResourcesOpenNow = (state) => {
  return getAllResources(state);
}

/* - - - - - - - - - SLICES - - - - - - - - - -  
A "slice" is a portion of the state, including all modifiers, 
pertaining to one React component.
First we initialize the slice. 
*/
const initialState = {
  list: [],
  status: "idle"
};

// Using createSlice will wrap mutable logic into safer immutable 
// logic and autogenerate actions etc. for the slice.
export const resourcesSlice = createSlice({
  name: 'resources',
  initialState, 
  reducers,
  extraReducers
});


/* - - - - - - - - - - ACTIONS - - - - - - - - - - -
An "action" is just a plain JS object that describes the action, 
with a "type" and "payload".
All it does is tell Redux which reducer to run on which slice.
Example: {type: "resources/updateList", payload: [] } 
Note: Creating a thunk creates a related action.
*/
// export const { updateList } = resourcesSlice.actions;

// Default export the reducers
export default resourcesSlice.reducer;