create type resource_type_enum as enum(
	'Helpline',
	'Shelter',
	'Support Centre',
	'Counselling Services',
	'Medical Centre',
	'Resource Bank',
	'Rehabilitation Centre',
	'Other',
	'Unknown'
);

create table resources (
	id serial not null primary key,
	created_at timestamp not null default now(),
	updated_at timestamp,
	resource_name varchar(256) unique not null,
	organization varchar(256),
	resource_type resource_type_enum not null default 'Unknown',
	address_street varchar(256),
	address_city varchar(64),
	phone_general varchar(32),
	phone_support varchar(32),
	email varchar(128),
	website varchar(256),
	open_247 boolean not null default false,
	hours jsonb,
	short_term boolean not null default false,
	long_term boolean not null default false,
	individual boolean not null default false,
	group_support boolean not null default false,
	free_access boolean not null default false,
	paid_access boolean not null default false,
	in_person boolean not null default false,
	by_phone boolean not null default false,
	video boolean not null default false,
	live_chat boolean not null default false,
	online boolean not null default false,
	drop_in boolean not null default false,
	appointment boolean not null default false,
	by_referral boolean not null default false,
	children boolean not null default false,
	youth boolean not null default false,
	adult boolean not null default false,
	all_ages boolean not null default false,
	families boolean not null default false,
	post_secondary boolean not null default false,
	non_binary boolean not null default false,
	men boolean not null default false,
	women boolean not null default false,
	all_genders boolean not null default false,
	queer boolean not null default false,
	trans boolean not null default false,
	black boolean not null default false,
	indigenous boolean not null default false,
	immigrant boolean not null default false,
	neurodiv boolean not null default false,
	disabled boolean not null default false,
	queer_friendly boolean not null default false,
	trans_friendly boolean not null default false,
	bipoc_friendly boolean not null default false,
	disability_friendly boolean not null default false,
	ndiv_friendly boolean not null default false,
	interpreter boolean not null default false,
	nurse boolean not null default false,
	sw boolean not null default false,
	ot boolean not null default false,
	psychotherapist boolean not null default false,
	psychologist boolean not null default false,
	shelter boolean not null default false,
	housing boolean not null default false,
	food boolean not null default false,
	hygeine boolean not null default false,
	counseling boolean not null default false,
	recreation boolean not null default false,
	peer_support boolean not null default false,
	resource_bank boolean not null default false,
	crisis boolean not null default false,
	medical boolean not null default false,
	referrals boolean not null default false,
	outreach boolean not null default false,
	employment boolean not null default false,
	legal boolean not null default false,
	abuse boolean not null default false,
	trauma boolean not null default false,
	addiction boolean not null default false,
	religions text[],
	languages text[]
);